### PR TITLE
Convert addon and example project to Godot 4

### PR DESCRIPTION
**Pull request by cridenour**
A simple conversion to get everything working smoothly in Godot 4.

### CODE REVIEW

**Comment by tavurth** [comment]
Cool! I'm guessing this no longer works with the 3.5 🤔 
I guess I can add this to a separate subfolder until then.

**Comment by cridenour** [comment]
@tavurth I have seen other projects use separate branches, which I believe the Godot Asset Library supports as well.

**Comment by tavurth** [comment]
Thank you!
Sorry for the slow delay :( I will check this and fix it up tomorrow if any bugs appear!

**Comment by cridenour** [comment]
I think I continued to tweak as 4.0 progressed - but I'm prepping for a release on Steam this week.

After things slow down, I'll try and bring over any additional changes!

**Comment by tavurth** [comment]
I'm also a little busy until next week but I will try to take a look and make some new releases when I have time.

Good luck with your release!

**Comment by tavurth** [comment]
Ok I had a chance to check it on my latest Godot 4.x looks good 👍 

I submitted a second 4.x release to the asset store

**Pull request merged**
